'pull_request_title': 'chore(localize): updated translation from Crowdin'
'pull_request_labels': ['crowdin']

files:
  - source: /src/services/i18n/locales/en/*.json
    translation: /src/services/i18n/locales/%locale%/%original_file_name%
